### PR TITLE
Patches of Hacker‘s morph

### PR DESCRIPTION
**Pull request by ghost**
Main modifications:

- Limb glow and color animation
- Add Animation action that can be controlled by animation

### CODE REVIEW

**Comment by mchorse** [comment]
This sounds epic! 😱

**Comment by mchorse** [comment]
It looks like I broke stuff when I was doing an internal rewrite. Don't worry about it @NyaNLI, I'll resolve conflicts when you'll be done with features (unless you're already done?).

**Comment by ghost** [comment]
Thank you McHorse, it's OK I'll resolve these conflects today or this weekend. And yeah I already finished all my features.

**Comment by mchorse** [comment]
> Thank you McHorse, it's OK I'll resolve these conflects today or this weekend. And yeah I already finished all my features.

Well, if you wish so. Thanks! 👍 

Edit: oh, you already fixed, that was so fast! 😱

**Pull request merged**
